### PR TITLE
Fix/1605 Options unique name not regenerated on clone

### LINKED ISSUE #1605: Copying a select field groups the Options across the fields when it shouldn't
Steps to reproduce:

1. Go to https://formbuilder.online/
2. Add a Select field
3. Copy that Select field
4. Now select any Option in Select field 1, the Option you selected in Select field 2 is cleared. It seems that the Options are grouped across the fields when it shouldn't be.

### PR DESCRIPTION
**Pull request by lucasnetau**
Cleanup for name generation in various places

* Use a unique name for the option group selectors, prevents clash when two fields have the same name
* Regenerate the unique name for the option group selectors on clone Fixes #1605 
* Regenerate item name on clone using the same method as creation (Utils.nameAttr) instead of rolling our own, prevents name clash on multiple clones in same millisecond

### CODE REVIEW

File: src/js/form-builder.js [hunk 1]
```diff
@@ -1609,8 +1609,7 @@ function FormBuilder(opts, element, $) {
 
     const currentId = currentItem.attr('id')
     const type = currentItem.attr('type')
-    const ts = new Date().getTime()
```
Comment (kevinchappell) [inline src/js/form-builder.js:1612]: in the future there is also the possibility to use `performance.now` in the `nameAttr` function for higher resolution time stamps

**Review by kevinchappell — APPROVED** [review]
looks good, works good. :+1:

File: src/js/form-builder.js (hunk 1 above)
Comment (lucasnetau) [reply src/js/form-builder.js:1612]: Yes. We really should be using `Date.now()` instead of `new Date().getTime()` to remove the object creation. We can also replace that call with `performance.timeOrigin + performance.now()`
