### PR TITLE
Initialise formRender in cases of undefined or empty formData

### LINKED ISSUE #1372: formRender options - setData does not work
### Screenshot
image

### PR DESCRIPTION
**Pull request by lucasnetau**
Ensure we initialise formRender even if there is no field data to render. This enables setData/render to be called after initialisation on an empty form

Fixes #1372

Update documentation for formRender actions

Small fix and tests applied to layout.js for lifting row/col fields

### CODE REVIEW

File: src/js/form-render.js [hunk 1]
```diff
@@ -28,7 +28,7 @@ class FormRender {
       container: false, // string selector or Node element
       dataType: 'json',
       disableHTMLLabels: false,
-      formData: false,
+      formData: [],
```
Comment (kevinchappell) [inline src/js/form-render.js:31]: :+1:

File: docs/formRender/actions/render.md [hunk 2]
```diff
@@ -1,6 +1,6 @@
 # `render` action
 
-Programmtically render or re-render a formRender instance with new data
+Programmatically render or re-render a formRender instance with new data
```
Comment (kevinchappell) [inline docs/formRender/actions/render.md:3]: whoops

**Review by kevinchappell — APPROVED** [review]

**Comment by kevinchappell** [comment]
@lucasnetau awesome work! thank you
