### PR TITLE
Fix formRender removing a valid empty userData array

### LINKED ISSUE #1514: checkbox is auto seleced when dragged and dropped, should be deselected initially when dragged and dropped
checkbox is auto seleced when dragged and dropped, should be deselected initially when dragged and dropped

### PR DESCRIPTION
**Pull request by lucasnetau**
select.js controls (Radio, Checkbox, Select) support an empty userData array. This was being filtered out by sanitizeField when putting the field data through trimObj.

This PR:

- fixes up the documentation for trimObj to document the removal of empty arrays
- ensures an empty userData array is returned while allowing trimObj to remove other invalid datatypes
- fixes a incorrect assignment when sanitising the value object
- adds additional tests to validate this behaviour

Fixes #1514

### CODE REVIEW

File: src/js/form-render.js [hunk 1]
```diff
@@ -156,9 +156,13 @@ class FormRender {
...
     delete sanitizedField.class
     if (field.values) {
-      field.values = field.values.map(option => utils.trimObj(option))
+      sanitizedField.values = field.values.map(option => utils.trimObj(option))
     }
-    return utils.trimObj(sanitizedField)
+    sanitizedField = utils.trimObj(sanitizedField)
+    if (Array.isArray(field.userData) && field.userData.length === 0) {
+      sanitizedField.userData = [] //Special handler for allowing userData to be empty
+    }
```
Comment (kevinchappell) [inline src/js/form-render.js:164]: :+1:

**Review by kevinchappell — APPROVED** [review]
